# Generated by Django 3.2.2 on 2021-05-11 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fah', '0005_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='type',
            field=models.ForeignKey(choices=[('Breakfast', 'Breakfast'), ('Starters', 'Starters'), ('Main course', 'Main Course'), ('Desert', 'Desert'), ('Snacks', 'Snacks'), ('Drinks', 'Drinks')], max_length=50, on_delete=django.db.models.deletion.CASCADE, to='fah.food_type'),
        ),
    ]
