# Generated by Django 3.2.2 on 2021-05-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fah', '0008_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food_type',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='food_items',
            new_name='Product',
        ),
    ]
